source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Rails gems
# gem 'rails', '~> 5.2'
gem 'rails', '~> 5.2', '>= 5.2.1'

gem 'sqlite3'

gem 'toastr-rails'

# gem 'pg'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

gem 'slim-rails', '~> 3.1', '>= 3.1.3'
gem 'jquery-rails'

gem 'authtrail'

gem 'font-awesome-sass', '~> 5.2.0'


gem 'bootsnap', '>= 1.1.0', require: false
gem 'bootstrap', '~> 4.1.3'

gem 'authtrail' # for Devise 
gem 'devise' 

gem 'acts-as-taggable-on', github: 'Fodoj/acts-as-taggable-on', branch: 'rails-5.2'

gem 'webpush'
gem 'simple_form'
gem 'geocoder', '~> 1.5'
gem 'gmaps4rails', '~> 2.1', '>= 2.1.2'
gem 'underscore-rails', '~> 1.8', '>= 1.8.3'


group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
